# -*- coding: utf-8 -*-
"""FLORA_FAUNA batch, translated per line and recomposed per row.

393 rows are built from only 379 distinct lines (918 instances). The template
is  name [+ description lines] + a taste/status verdict, so the table below is
organised the same way and the 'X captured alive' family is generated from the
species glossary rather than written out.

Row slack is 0-1 byte, so each Korean line must fit inside the byte length of
the English line it replaces. Species names are the ones already fixed in the
FOOD/MEDICINE batches (바이칼 비늘치, 러시아 가짜망고, 유럽토끼 ...); the
taste ladder is the same one FOOD uses.
"""
import sys
import os
import importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_s = importlib.util.spec_from_file_location(
    'lb', os.path.join(ROOT, 'tools/mgs3d_stage_line_batch.py'))
lb = importlib.util.module_from_spec(_s)
sys.modules['lb'] = lb
_s.loader.exec_module(lb)

NAMES = {
    'Arowana': '아로와나',
    'Baikal Scaly Tooth': '바이칼 비늘치',
    'Baltic Hornet Nest': '발트 말벌집',
    'Bigeye Trevally': '큰눈전갱이',
    'Calorie Mate': '칼로리 메이트',
    'Cobalt Blue Tarantula': '코발트블루 타란툴라',
    'Coral Snake': '산호뱀',
    'Emperor Scorpion': '황제전갈',
    'European Rabbit': '유럽토끼',
    'Fly Agaric': '광대버섯',
    'Giant Anaconda': '대왕 아나콘다',
    'Golova': '골로바',
    'Green Tree Python': '그린 트리 파이톤',
    'Indian Gavial': '인도 가비알',
    'Instant Noodles': '인스턴트 라면',
    'Japanese Flying Squirrel': '일본하늘다람쥐',
    'Kenyan Mangrove Crab': '케냐 맹그로브 게',
    'King Cobra': '킹코브라',
    'Liquid': '리퀴드',
    'Magpie': '까치',
    'Markhor': '마코르',
    'Maroon Shark': '마룬 샤크',
    'Milk Snake': '우유뱀',
    'Otton Frog': '오톤개구리',
    'Parrot': '앵무새',
    'Poison Dart Frog': '독화살개구리',
    'Rat': '쥐',
    'Ration': '레이션',
    'Red Avadavat': '홍작',
    'Reticulated Python': '그물무늬비단뱀',
    'Russian False Mango': '러시아 가짜망고',
    'Russian Glowcap': '러시아 발광버섯',
    'Russian Oyster Mushroom': '러시아 느타리버섯',
    'Siberian Ink Cap': '시베리아 먹물버섯',
    'Solid': '솔리드',
    'Solidus': '솔리더스',
    'Spatsa': '스파차',
    'Sunda Whistling-Thrush': '순다 휘파람지빠귀',
    'Taiwanese Cobra': '대만코브라',
    'Thai Cobra': '태국코브라',
    'Tree Frog': '청개구리',
    'Tsuchinoko': '츠치노코',
    'Ural Luminescent Mushroom': '우랄 발광버섯',
    'Vampire Bat': '흡혈박쥐',
    'Vine Melon': '덩굴 멜론',
    'White-Rumped Vulture': '흰등독수리',
    'White-rumped Vulture': '흰등독수리',
    'Yabloko Moloko': '야블로코 몰로코',
}

TASTE = {
    # not eaten yet
    'Not eaten yet. Taste unknown.': '미섭취. 맛 불명.',
    'Not eaten yet. Said to be not bad.': '미섭취. 나쁘지 않다고 한다.',
    'Not eaten yet. Said to be fairly tasty.': '미섭취. 제법 맛있다고 한다.',
    'Not eaten yet. Said not to be very good.': '미섭취. 맛은 별로라고 한다.',
    'Not eaten yet. Said to be very tasty!': '미섭취. 아주 맛있다고 한다!',
    'Not eaten yet. Said to be tasty.': '미섭취. 맛있다고 한다.',
    'Not eaten yet. Said to be poisonous.': '미섭취. 독이 있다고 한다.',
    'Not eaten yet. Said to taste bad.': '미섭취. 맛없다고 한다.',
    'Not eaten yet. Known to be edible.': '미섭취. 먹을 수 있다고 한다.',
    'Not eaten yet. Was not told how it tastes.': '미섭취. 맛은 듣지 못했다.',
    'Not eaten yet. Said to taste not half-bad.': '미섭취. 제법이라고 한다.',
    'Not eaten yet. Said it could be poisonous.': '미섭취. 독이 있을지 모른다.',
    'Not eaten yet. Supposed to taste great.': '미섭취. 아주 맛있다고 한다.',
    'Not eaten yet, but said to be tasty.': '미섭취. 맛있다고 한다.',
    'Not eaten yet, but said to be edible.': '미섭취. 먹을 수 있다고 한다.',
    'Not eaten yet, but said to be edible in a pinch.': '미섭취. 급하면 먹을 수 있다고 한다.',
    'Not eaten yet. Said it could cause food poisoning.': '미섭취. 식중독을 일으킬 수 있다고 한다.',
    'Not eaten yet. Said to be extremely poisonous.': '미섭취. 맹독이 있다고 한다.',
    'Not eaten yet. Said to be so tasty.': '미섭취. 매우 맛있다고 한다.',
    'Not eaten yet. Said to be quite tasty.': '미섭취. 상당히 맛있다고 한다.',
    'Not eaten yet. Was told the taste is unknown.': '미섭취. 맛은 모른다고 들었다.',
    'Not eaten yet. Was told to try the taste.': '미섭취. 먹어보라고 들었다.',
    'Not eaten yet. Said to be pretty tasty.': '미섭취. 꽤 맛있다고 한다.',
    'Not eaten yet. Said to taste terrible.': '미섭취. 맛이 끔찍하다고 한다.',
    "Not eaten yet, but it doesn't look very good.": '미섭취. 맛있어 보이지는 않는다.',
    'Taste unknown, but said to be edible.': '맛은 모르나 먹을 수 있다고 한다.',
    'Taste unknown. Possibly edible.': '맛 불명. 먹을 수 있을 듯.',
    'Taste and details unknown.': '맛도 정보도 불명.',
    'Known to be edible.': '먹을 수 있다.',
    'to be edible.': '먹을 수 있다.',
    'Said that the taste is unknown.': '맛은 모른다고 한다.',
    'Was told the taste is unknown.': '맛은 모른다고 들었다.',
    'Was told to try the taste.': '먹어보라고 들었다.',
    "Wasn't told how it tastes.": '맛은 듣지 못했다.',
    "Asked about flavor, but wasn't answered.": '맛을 물었지만 답을 듣지 못했다.',

    # eaten
    'Tried it. Tasted terrible.': '먹어봤다. 맛이 끔찍했다.',
    'Tried it. Was pretty tasty.': '먹어봤다. 꽤 맛있었다.',
    'Tried it. Not half bad.': '먹어봤다. 괜찮았다.',
    'Tried it. Was fairly tasty.': '먹어봤다. 제법 맛있었다.',
    'Tried it. Was not bad.': '먹어봤다. 괜찮았다.',
    'Tried it. Caused food poisoning.': '먹어봤다. 식중독에 걸렸다.',
    'Tried it. Unbelievably tasty!': '먹어봤다. 믿을 수 없는 맛!',
    'Tried it. Not very good.': '먹어봤다. 별로였다.',
    'Tried it. Was quite tasty.': '먹어봤다. 상당히 맛있었다.',
    'Tried it. Was tasty.': '먹어봤다. 맛있었다.',
    'Tried it. Not bad.': '먹어봤다. 괜찮았다.',
    'Tried it. Tasted great.': '먹어봤다. 아주 맛있었다.',
    'Tried it. Tasted bad.': '먹어봤다. 맛없었다.',
    'Tried it. Not too bad.': '먹어봤다. 나쁘지 않았다.',
    'Tried it. Was very tasty.': '먹어봤다. 매우 맛있었다.',
    'Tasted bad.': '맛없었다.',
    'Tasted terrible.': '맛이 끔찍했다.',
    'Was not bad.': '괜찮았다.',
    'Not half bad.': '제법이었다.',
    'Was pretty tasty.': '꽤 맛있었다.',
    'Was fairly tasty.': '제법 맛있었다.',
    'Was quite tasty.': '상당히 맛있었다.',
    'Was very tasty.': '매우 맛있었다.',
    'Unbelievably tasty!': '믿을 수 없는 맛!',
    'It was unbelievably tasty!': '믿을 수 없이 맛있었다!',
    'Excellent taste!': '최고의 맛!',
    'Not too bad.': '나쁘지 않았다.',
    'Was poisonous.': '독이 있었다.',
    'Caused food poisoning.': '식중독에 걸렸다.',
    'Caused food poisoning when eaten.': '먹었더니 식중독에 걸렸다.',
    'Was said to be edible, but caused food poisoning': '먹을 수 있다고 했지만 먹었더니',
    'when eaten.': '식중독에 걸렸다.',
    'Became sleepy after eating.': '먹은 뒤 졸음이 왔다.',
    'Became sleepy after eating it, possibly due to': '먹은 뒤 졸음이 왔다. 마취 성분이 있는',
    'a vegetative alkaloid with anesthetic properties.': '식물성 알칼로이드 때문인 듯하다.',
    'Not exactly sure why, but became sleepy after': '이유는 모르겠지만 먹은 뒤',
    'eating it.': '졸음이 왔다.',
    "Seems to have been someone's pet. Told not to": '누군가의 애완동물이었던 듯하다.',
    'eat it.': '먹지 말라고 들었다.',
    "Seems to have been someone's pet.": '누군가의 애완동물이었던 듯하다.',
    'This bird looks familiar.': '어디서 본 듯한 새다.',
}

CAPTURED = {}
for _en, _ko in NAMES.items():
    CAPTURED['%s captured alive' % _en] = '%s 생포' % _ko

DESC = {
    'Arowana. A large fish.': '아로와나. 큰 물고기.',
    'Arowana. An ancient fish that inhabits tropical': '아로와나. 열대 담수에 사는 고대어.',
    'freshwaters. Too big to be captured alive.': '너무 커서 생포할 수 없다.',
    'Baikal Scaly Tooth. A brown mushroom.': '바이칼 비늘치. 갈색 버섯.',
    'Baltic Hornet Nest. A hornet nest.': '발트 말벌집. 말벌의 둥지.',
    'Baltic Hornet Nest. Contains hornets controlled': '발트 말벌집. 페인이 조종하는',
    'by The Pain.': '말벌이 들어 있다.',
    'Filled with honey and hornets controlled by': '꿀과 페인이 조종하는 말벌이',
    'The Pain.': '가득하다.',
    'Baltic Hornet Nest. The nest of the Baltic hornet,': '발트 말벌집. 이 지역에만 사는',
    'a type of hornet found only in this region.': '발트 말벌의 둥지.',
    'Baltic Hornet Nest. The nest of the Baltic hornet.': '발트 말벌집. 이 지역에만 사는',
    'A type of hornet found only in this region.': '발트 말벌의 둥지.',
    'Filled with honey. Not eaten yet. Said to be very': '꿀이 가득하다. 미섭취.',
    'tasty!': '맛있다고!',
    'Filled with honey. Tried it. Was very tasty.': '꿀이 가득하다. 먹어봤다. 매우 맛있었다.',
    "Baltic Hornet Nest with The Pain's hornets": '페인의 말벌이 든 발트 말벌집',
    'Bigeye Trevally. A fish with silver eyes.': '큰눈전갱이. 은빛 눈의 물고기.',
    'Bigeye Trevally. A member of the mackerel family.': '큰눈전갱이. 고등어과 물고기.',
    'Inhabits coastal and brackish waters in tropical and': '열대와 아열대의 연안과 기수역에 산다.',
    'subtropical regions. The adult fish live around coral': '다 자란 개체는 산호초 주변에',
    'reefs.': '산다.',
    'Calorie Mate. A balanced nutrition food invented in': '칼로리 메이트. 일본에서 개발된',
    'Japan.': '균형 영양식.',
    'Contains a healthy balance of all five major': '단백질, 지방, 탄수화물, 비타민,',
    'nutrients : protein, fat, carbohydrates, vitamins,': '미네랄 5대 영양소를 고루 함유.',
    'and minerals.': '영양 균형이 좋다.',
    'Calorie Mate. Never seen a food like this before.': '칼로리 메이트. 처음 보는 음식이다.',
    'Cobalt Blue Tarantula. A large spider.': '코발트블루 타란툴라. 큰 거미.',
    'Cobalt Blue Tarantula. A venomous spider with': '코발트블루 타란툴라. 강한 독을 지닌',
    'a powerful venom.': '독거미.',
    'Makes its home primarily in underground nests.': '주로 땅속에 둥지를 튼다.',
    'Highly aggressive and capable of catching prey as': '매우 공격적이며 쥐나 뱀만 한',
    'large as mice and snakes.': '먹이도 사냥한다.',
    'Coral Snake. A brightly colored snake.': '산호뱀. 화려한 빛깔의 뱀.',
    'Coral Snake. A venomous snake native to': '산호뱀. 아메리카 대륙 토종',
    'the Americas.': '독사.',
    'Carries an extremely potent neurotoxin.': '매우 강한 신경독을 지닌다.',
    'Carries a potent neurotoxin.': '강한 신경독을 지닌다.',
    'Carries a potent neurotoxin. Highly aggressive.': '강한 신경독을 지닌다. 매우 공격적.',
    'Emperor Scorpion. A large scorpion.': '황제전갈. 큰 전갈.',
    'Emperor Scorpion. The largest scorpion in': '황제전갈. 세계에서 가장 큰',
    'the world.': '전갈.',
    'European Rabbit. An ordinary rabbit.': '유럽토끼. 평범한 토끼.',
    'Fly Agaric. A red mushroom.': '광대버섯. 붉은 버섯.',
    'Fly Agaric. A type of agaric mushroom found': '광대버섯. 첼리노야르스크에만 나는',
    'only in Tselinoyarsk. Extremely poisonous.': '광대버섯류. 맹독이 있다.',
    'only in Tselinoyarsk.': '버섯.',
    'Giant Anaconda. A large snake with black spots.': '대왕 아나콘다. 검은 반점의 큰 뱀.',
    'Giant Anaconda. The largest snake in the world': '대왕 아나콘다. 무게와 지름 기준',
    'in terms of weight and diameter. Not venomous.': '세계 최대의 뱀. 독은 없다.',
    'Native to South America.': '남아메리카 토종.',
    'Golova. A large fruit.': '골로바. 큰 열매.',
    'Golova. A type of jackfruit that grows only in': '골로바. 첼리노야르스크에만 자라는',
    'Tselinoyarsk.': '잭프루트류.',
    'Golova means "head," and the fruit was so named': '골로바는 "머리"라는 뜻으로, 사람 머리만',
    'because it grows to about the size of a human': '하게 자라서 붙은',
    'head.': '이름이다.',
    'Green Tree Python. A large snake native to': '그린 트리 파이톤. 오스트레일리아와',
    'Australia and New Zealand. Not venomous.': '뉴질랜드 토종 큰 뱀. 독은 없다.',
    'Green Tree Python. A large, green snake.': '그린 트리 파이톤. 크고 초록빛인 뱀.',
    'Indian Gavial. A large crocodile that inhabits the': '인도 가비알. 인도와 네팔의 담수에',
    'fresh waters of India and Nepal. Normally a timid': '사는 큰 악어. 원래는 겁이 많으나',
    'creature, but driven mad by nuclear testing.': '핵실험으로 광포해졌다.',
    'Indian Gavial. A large crocodile.': '인도 가비알. 큰 악어.',
    'Instant Noodles. Apparently turns into a noodle': '인스턴트 라면. 면 요리가',
    'meal.': '된다고 한다.',
    "Instant Noodles. The world's first instant noodles,": '인스턴트 라면. 일본에서 개발된',
    'invented in Japan.': '세계 최초의 라면.',
    "Just add hot water and they're ready to eat.": '뜨거운 물만 부으면 바로 먹을 수 있다.',
    'Japanese Flying Squirrel. A large flying squirrel.': '일본하늘다람쥐. 큰 하늘다람쥐.',
    'Japanese Flying Squirrel. A member of the squirrel': '일본하늘다람쥐. 다람쥐과 동물.',
    'family. A membrane of skin stretching between its': '목, 앞다리, 뒷다리, 꼬리 사이의',
    'neck, front legs, hind legs, and tail allows it to': '피막으로 나무에서 나무로',
    'glide from tree to tree.': '활공한다.',
    'Kenyan Mangrove Crab. A land-dwelling crab found': '케냐 맹그로브 게. 남아프리카, 인도,',
    'in South Africa, India, Polynesia, and other places.': '폴리네시아 등지에 사는 육상 게.',
    'Kenyan Mangrove Crab. A large crab.': '케냐 맹그로브 게. 큰 게.',
    'King Cobra. A large, gray snake.': '킹코브라. 크고 잿빛인 뱀.',
    'King Cobra. One of the largest snakes in the world.': '킹코브라. 세계에서 가장 큰 뱀 중 하나.',
    'Its bite can kill even an elephant. Native to': '물리면 코끼리도 죽는다.',
    'Southeast Asia.': '동남아시아 토종.',
    'Liquid. A mysterious white snake.': '리퀴드. 신비한 흰 뱀.',
    'Solid. A mysterious white snake.': '솔리드. 신비한 흰 뱀.',
    'Solidus. A mysterious white snake.': '솔리더스. 신비한 흰 뱀.',
    'Magpie. A bird with a long tail.': '까치. 꼬리가 긴 새.',
    'Magpie. A member of the crow family. Native to': '까치. 까마귀과의 새. 북아메리카와',
    'North America and the Eurasian continent.': '유라시아 대륙에 서식.',
    'Distinguished by its beautiful dark blue and': '아름다운 짙은 청색과 흰색 몸통,',
    'white body and its long tail.': '긴 꼬리가 특징.',
    'Markhor. A large goat.': '마코르. 큰 염소.',
    'Markhor. A wild goat that lives in mountainous': '마코르. 히말라야를 비롯한 산악 지대에',
    'regions including the Himalayas.': '사는 야생 염소.',
    'The name "markhor" apparently means': '"마코르"는 뱀을 먹는 자라는',
    'snake eater. Cannot be captured alive.': '뜻이라고 한다. 생포는 불가.',
    'Maroon Shark. A fish resembling a carp.': '마룬 샤크. 잉어 비슷한 물고기.',
    'Maroon Shark. A member of the carp family native': '마룬 샤크. 동남아시아에 사는',
    'to Southeast Asia.': '잉어과 물고기.',
    'Milk Snake. A brightly colored snake.': '우유뱀. 화려한 빛깔의 뱀.',
    'Milk Snake. Native to the Americas. Closely': '우유뱀. 아메리카 대륙 토종.',
    'resembles the coral snake, but is not venomous.': '산호뱀과 닮았지만 독은 없다.',
    'Otton Frog. A large frog.': '오톤개구리. 큰 개구리.',
    'Otton Frog. A rare frog found only on Amami': '오톤개구리. 아마미오섬에만 사는',
    'Oshima Island. Distinguished by its five-toed feet.': '희귀종. 발가락이 다섯인 것이 특징.',
    'Parrot. A very talkative parrot native to Indochina.': '앵무새. 인도차이나 토종의 수다스러운 새.',
    'Parrot. This bird looks familiar.': '앵무새. 어디서 본 듯한 새다.',
    'Poison Dart Frog. A brightly colored frog.': '독화살개구리. 화려한 빛깔의 개구리.',
    'Poison Dart Frog. A frog native to Central': '독화살개구리. 중남미 토종',
    'and South America.': '개구리.',
    'Rat. A common rat.': '쥐. 흔한 쥐.',
    'Rat. A type of wild brown rat bred by humans as': '쥐. 사람이 애완용, 실험용으로 기르는',
    'pets and lab animals.': '야생 시궁쥐의 일종.',
    'Ration. A portable ration issued by the Russian': '레이션. 러시아군이 지급하는',
    'military.': '휴대 식량.',
    'Red Avadavat. A small bird native to southern': '홍작. 중국 남부와 동남아시아 토종의',
    'China and Southeast Asia.': '작은 새.',
    'Currently in its mating season, so its colors': '지금은 번식기라 빛깔이',
    'are brilliant.': '선명하다.',
    'Red Avadavat. A small red bird.': '홍작. 작고 붉은 새.',
    'Reticulated Python. A large snake characterized by': '그물무늬비단뱀. 그물 무늬가 특징인',
    'a mesh pattern.': '큰 뱀.',
    'Reticulated Python. The longest snake in the': '그물무늬비단뱀. 세계에서 가장 긴 뱀.',
    'world. Not venomous. Native to Southeast Asia.': '독은 없다. 동남아시아 토종.',
    'Russian False Mango. A yellow fruit.': '러시아 가짜망고. 노란 열매.',
    'Russian Glowcap. A glowing mushroom that can': '러시아 발광버섯. 첼리노야르스크 부근에만',
    'only be found in the vicinity of Tselinoyarsk.': '나는 빛나는 버섯.',
    'Russian Glowcap : Not eaten yet.': '러시아 발광버섯 : 미섭취.',
    'Said to recharge the battery when eaten.': '먹으면 배터리가 충전된다고 한다.',
    "Because it's a glowing mushroom, it recharged": '빛나는 버섯이라 먹었더니',
    'the battery after eating.': '배터리가 충전됐다.',
    "Because it's a glowing mushroom, it supposedly": '빛나는 버섯이라 먹으면',
    'recharges the battery when eaten.': '배터리가 충전된다고 한다.',
    'Russian Glowcap. A glowing mushroom.': '러시아 발광버섯. 빛나는 버섯.',
    'Russian Glowcap. A glowing mushroom. Recharged': '러시아 발광버섯. 빛나는 버섯.',
    "the battery after eating. Just what you'd expect": '먹었더니 배터리가 충전됐다.',
    'from a glowing mushroom.': '과연 발광버섯답다.',
    'Russian Oyster Mushroom. A flat-headed': '러시아 느타리버섯. 갓이 납작한',
    'mushroom.': '버섯.',
    'Russian Oyster Mushroom. A mushroom of the': '러시아 느타리버섯. 첼리노야르스크에만',
    'shimeji family found only in Tselinoyarsk. Known': '나는 만가닥버섯과 버섯.',
    'Siberian Ink Cap. A brown mushroom.': '시베리아 먹물버섯. 갈색 버섯.',
    'Siberian Ink Cap. A type of glowcap mushroom': '시베리아 먹물버섯. 첼리노야르스크 부근에만',
    'found only in the vicinity of Tselinoyarsk.': '나는 발광버섯류.',
    'Siberian Ink Cap. A type of inkcap mushroom': '시베리아 먹물버섯. 첼리노야르스크 부근에만',
    'found only in the vicinity of Tselinoyarsk. Known': '나는 먹물버섯류.',
    'Spatsa. A grey mushroom.': '스파차. 회색 버섯.',
    'Sunda Whistling-Thrush. A bird distinguished by its': '순다 휘파람지빠귀. 긴 부리와 크고 푸른',
    'long beak and large blue body. Native to Java and': '몸이 특징인 새. 자바와 수마트라',
    'Sumatra.': '토종.',
    'Sunda Whistling-Thrush. A large black bird.': '순다 휘파람지빠귀. 크고 검은 새.',
    'Taiwanese Cobra. A snake marked with': '대만코브라. 안경 무늬가 있는',
    'a spectacle pattern.': '뱀.',
    'Taiwanese Cobra. A snake that inhabits Taiwan': '대만코브라. 대만과 중국 남부에',
    'and southern China.': '사는 뱀.',
    'Thai Cobra. A brown snake.': '태국코브라. 갈색 뱀.',
    'Thai Cobra. A venomous snake native to Thailand,': '태국코브라. 태국, 인도차이나, 중국 남부',
    'Indochina, and southern China.': '토종 독사.',
    'Tree Frog. A frog found throughout Asia.': '청개구리. 아시아 전역에 사는 개구리.',
    'Arboreal. Lives in small trees and bushes.': '나무 위에서 살며 작은 나무와 덤불에 산다.',
    'Tree Frog. An oddly large tree frog.': '청개구리. 유난히 큰 청개구리.',
    'Tsuchinoko. An Unidentified Mysterious Animal.': '츠치노코. 정체불명의 미확인 동물.',
    'Often spotted in Japan. Known as the "phantom': '일본에서 자주 목격된다. "환상의 뱀"으로',
    'snake."': '불린다.',
    'Tsuchinoko. Never seen a snake like this before.': '츠치노코. 처음 보는 뱀이다.',
    'At first glance, looks like a shiitake.': '얼핏 보면 표고버섯 같다.',
    'At first glance, looks like a shiitake, but it is': '얼핏 보면 표고버섯 같지만',
    'poisonous.': '독이 있다.',
    'Ural Luminescent Mushroom. A mushroom of the': '우랄 발광버섯. 이 지역에서만 나는',
    'shimeji family that can only be found in this region.': '만가닥버섯과 버섯.',
    'Ural Luminescent Mushroom. A mushroom that': '우랄 발광버섯. 표고버섯을 닮은',
    'resembles a shiitake.': '버섯.',
    'Ural Luminescent Mushroom. A mushroom': '우랄 발광버섯. 표고버섯을',
    'that resembles a shiitake.': '닮은 버섯.',
    'Vampire Bat. A large bat.': '흡혈박쥐. 큰 박쥐.',
    'Vampire Bat. A blood-sucking bat. Drains stamina': '흡혈박쥐. 피를 빠는 박쥐. 피를 빨며',
    'as it sucks blood. Not eaten yet, but said to be': '스태미나를 앗아간다. 미섭취.',
    'edible in a pinch.': '급하면 먹을 수 있다고 한다.',
    'Vampire Bat. A blood-sucking bat.': '흡혈박쥐. 피를 빠는 박쥐.',
    'Drains stamina as it sucks blood.': '피를 빨며 스태미나를 앗아간다.',
    'Vine Melon. A melon that grows on a vine.': '덩굴 멜론. 덩굴에 열리는 멜론.',
    'Vine Melon. A type of vine-growing melon found': '덩굴 멜론. 첼리노야르스크에만 나는',
    'only in Tselinoyarsk. Full of nutrients.': '덩굴 멜론류. 영양이 풍부하다.',
    'White-Rumped Vulture. A large bird of prey found': '흰등독수리. 인도에 사는 큰 맹금.',
    'in India. Feeds primarily on dead flesh. Cannot be': '주로 죽은 고기를 먹는다.',
    'captured alive.': '생포는 불가.',
    'White-Rumped Vulture. A large vulture.': '흰등독수리. 큰 독수리.',
    'Yabloko Moloko. A fruit resembling a star apple': '야블로코 몰로코. 첼리노야르스크에만',
    'that grows only in the Tselinoyarsk region.': '자라는 스타애플 비슷한 열매.',
    'Yabloko moloko means "apple dripping with milk."': '"우유가 흐르는 사과"라는 뜻.',
    'Cutting it open lengthwise reveals a distinctive': '세로로 가르면 특유의 별 모양',
    'star-shaped band inside.': '무늬가 드러난다.',
    'Yabloko moloko. A red fruit.': '야블로코 몰로코. 붉은 열매.',
}

MISC = {
    'Operation Snake Eater completed.': '스네이크 이터 작전 완료.',
    'OPERATION SNAKE EATER': '스네이크 이터 작전',
    'Commencing Operation Snake Eater': '스네이크 이터 작전 개시',
    'Condition :': '조건 :',
    'Clear the game with the': '츠치노코를 생포한 채로',
    'Tsuchinoko captured alive.': '게임을 클리어한다.',
    'Hint :': '힌트 :',
    'Awarded to those who capture': '전설의 뱀을 산 채로 잡아',
    'the legendary snake alive and': '가지고 돌아온 자에게',
    'bring it back.': '주어진다.',
    'Snake pattern camo uniform. Provides the ultimate': '뱀 무늬 위장복. 어떤 환경에서도',
    'cover in any environment.': '최고의 은폐 효과.',
    'UNIFORM/SNAKE': '위장복/뱀',
    'SPIDER': '거미',
    'CENTIPEDE': '지네',
    'TORTOISE': '거북',
    'FISH A': '어류A',
    'FISH B': '어류B',
    'BIRD E': '새E',
}
for _p, _kop in (('R.BIRD', '새'), ('R.FISH', '어'), ('R.SNAKE', '뱀')):
    for _c in 'ABCDEFG':
        MISC['%s %s' % (_p, _c)] = '희귀%s%s' % (_kop, _c)
MISC['R.SPIDER'] = '희귀거미'

T = {}
for _d in (NAMES, CAPTURED, TASTE, DESC, MISC):
    T.update(_d)

if __name__ == '__main__':
    lb.run_batch('FLORA_FAUNA', T, 'STAGE_FLORA_FAUNA_2026-08-19')
