#!/usr/bin/env python3
"""Build a validated codec translation JSON from the PS2대응없음 review batch.

Reads the master codec review CSV, takes every status=PS2대응없음 row with
a non-empty `korean` value, normalizes known corpus defects, and writes an
`mgs3d-codec-translation-v1` JSON. Rows with unresolved defects are excluded
and reported separately rather than guessed at.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

STATUS_PS2NONE = "PS2대응없음"

ZERO_WIDTH = "​"
ELLIPSIS = "…"
TOKEN2 = re.compile(r"<[0-9A-Fa-f]{2}>")
TOKEN_WIDE = re.compile(r"<([0-9A-Fa-f]{4})>")
BRACKET = re.compile(r"[<>]")


def split_wide_tokens(text: str) -> str:
    return TOKEN_WIDE.sub(lambda m: f"<{m.group(1)[:2]}><{m.group(1)[2:]}>", text)


def escape_literal_brackets(text: str) -> str:
    """Escape '<'/'>' not part of a valid <HH> token, e.g. quoted titles."""
    out = []
    cursor = 0
    while cursor < len(text):
        match = TOKEN2.match(text, cursor)
        if match:
            out.append(match.group(0))
            cursor = match.end()
            continue
        char = text[cursor]
        if char == "<":
            out.append("<3C>")
        elif char == ">":
            out.append("<3E>")
        else:
            out.append(char)
        cursor += 1
    return "".join(out)


def normalize(text: str) -> str:
    text = text.replace(ZERO_WIDTH, "")
    text = text.replace(ELLIPSIS, "...")
    text = split_wide_tokens(text)
    text = escape_literal_brackets(text)
    return text


def load_rows(path: Path) -> list[dict[str, str]]:
    csv.field_size_limit(sys.maxsize)
    with path.open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("review", type=Path, help="master codec-3ds-INTEGRATED-review.csv")
    parser.add_argument("output", type=Path, help="output mgs3d-codec-translation-v1 JSON")
    parser.add_argument("--flagged-output", type=Path, help="rows excluded for manual review")
    args = parser.parse_args()

    rows = load_rows(args.review)
    filled = [row for row in rows
              if row.get("status") == STATUS_PS2NONE and row.get("korean", "").strip()]

    units = []
    flagged = []
    for row in filled:
        text = normalize(row["korean"])
        stripped = TOKEN2.sub("", text)
        bad_chars = sorted({
            ch for ch in stripped
            if not (0x20 <= ord(ch) <= 0x7E) and not (0xAC00 <= ord(ch) <= 0xD7A3)
        })
        if bad_chars:
            flagged.append({
                "gcx": row["gcx"], "resource": row["resource"],
                "korean": row["korean"], "bad_chars": bad_chars,
            })
            continue
        units.append({
            "gcx": int(row["gcx"]),
            "resource": int(row["resource"]),
            "kind": "string",
            "original_size": len(row.get("raw_text", "")),
            "text": text,
        })

    document = {
        "format": "mgs3d-codec-translation-v1",
        "note": "PS2대응없음 batch, generated by mgs3d_codec_ps2none_translation_build.py",
        "character_map": {},
        "units": units,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if args.flagged_output:
        args.flagged_output.parent.mkdir(parents=True, exist_ok=True)
        args.flagged_output.write_text(
            json.dumps({"flagged_count": len(flagged), "flagged": flagged}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

    print(f"total_filled={len(filled)} clean_units={len(units)} flagged={len(flagged)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
